### ISSUE TITLE
Elementa library conflict with Craftify

### ISSUE THREAD

**Issue by Tobias20084** [DeDiamondPro/Resourcify#9] opened 2023-07-06 18:42 UTC
**Technical Information**
Resourcify version: 1.20.x (1.1.0)
Minecraft version: 1.20.1
Other mods (if relevant): 

AmbientSounds_FABRIC_v5.2.20_mc1.20.1.jar
appleskin-fabric-mc1.20-2.5.0.jar
blur-3.1.0.jar
borderless-mining-1.1.8+1.20.1.jar
CameraOverhaul-1.4.0-fabric-universal.jar
cloth-config-11.0.99-fabric.jar
Craftify-1.20.1-1.11.0-fabric.jar
CreativeCore_FABRIC_v2.10.24_mc1.20.1.jar
dynamiccrosshair-7.0.2+1.20-fabric.jar
explosive-enhancement-1.1.0-1.20.x.jar
extendedclouds-1.2.2+1.20.jar
fabric-api-0.84.0+1.20.1.jar
fabric-language-kotlin-1.10.0+kotlin.1.9.0.jar
ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric.jar
grasskiss-1.20-fabric0.83.0-0.5.0.jar
InvMove-1.20-0.8.4-Fabric.jar
iris-mc1.20-1.6.4.jar
modelfix-1.14-fabric.jar
modmenu-7.1.0.jar
MouseTweaks-fabric-mc1.20-2.25.jar
pinglist-1.4.jar
Resourcify (1.20.x-fabric)-1.1.0.jar
sodium-fabric-mc1.20-0.4.10+build.27.jar
Sort-1.0.3.jar
switcheroo-1.0.11+1.20.jar
yet-another-config-lib-fabric-3.0.3+1.20.jar

**Describe the bug**
clicking on one of the resources packs resolves in a crash.

**Expected behavior**
Opens the browser with the resource pack

**Log File**
[20:35:23] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.21
[20:35:23] [main/INFO]: Loading 107 mods:
	- ambientsounds 5.2.20
	- appleskin 2.5.0+mc1.20
	- blur 3.1.0
	   |-- midnightlib 1.4.1
	   \-- satin 1.13.0
	- borderlessmining 1.1.8+1.20.1
	   \-- fabric-resource-loader-v0 0.11.7+f7923f6d82
	- cameraoverhaul 1.4.0-fabric-universal
	- cloth-config 11.0.99
	   \-- cloth-basic-math 0.6.1
	- craftify 1.11.0
	   |-- elementa 590
	   |-- universalcraft 277
	   \-- vigilance 284
	- creativecore 2.10.24
	   \-- net_minecraftforge_eventbus 6.0.3
	- dynamiccrosshair 7.0.2+1.20
	   |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	   \-- yaclx 1.1+1.20
	- explosiveenhancement 1.1.0-1.20.x
	- extendedclouds 1.2.2+1.20
	- fabric-api 0.84.0+1.20.1
	   |-- fabric-api-base 0.4.29+b04edc7a77
	   |-- fabric-api-lookup-api-v1 1.6.34+4d8536c977
	   |-- fabric-biome-api-v1 13.0.10+b3afc78b77
	   |-- fabric-block-api-v1 1.0.9+e022e5d177
	   |-- fabric-blockrenderlayer-v1 1.1.39+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.0.20+b3afc78b77
	   |-- fabric-command-api-v1 1.2.32+f71b366f77
	   |-- fabric-command-api-v2 2.2.11+b3afc78b77
	   |-- fabric-commands-v0 0.2.49+df3654b377
	   |-- fabric-containers-v0 0.1.61+df3654b377
	   |-- fabric-content-registries-v0 4.0.7+b3afc78b77
	   |-- fabric-convention-tags-v1 1.5.3+b3afc78b77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.1.11+b3afc78b77
	   |-- fabric-dimensions-v1 2.1.51+b3afc78b77
	   |-- fabric-entity-events-v1 1.5.21+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.0+b3afc78b77
	   |-- fabric-events-lifecycle-v0 0.2.61+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a77
	   |-- fabric-item-api-v1 2.1.26+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.7+b3afc78b77
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b77
	   |-- fabric-loot-api-v2 1.1.37+b3afc78b77
	   |-- fabric-loot-tables-v1 1.1.41+9e7660c677
	   |-- fabric-message-api-v1 5.1.6+b3afc78b77
	   |-- fabric-mining-level-api-v1 2.1.47+b3afc78b77
	   |-- fabric-models-v0 0.3.35+b3afc78b77
	   |-- fabric-networking-api-v1 1.3.8+b3afc78b77
	   |-- fabric-networking-v0 0.3.48+df3654b377
	   |-- fabric-object-builder-api-v1 11.0.6+b3afc78b77
	   |-- fabric-particles-v1 1.0.28+b3afc78b77
	   |-- fabric-recipe-api-v1 1.0.18+b3afc78b77
	   |-- fabric-registry-sync-v0 2.2.6+b3afc78b77
	   |-- fabric-renderer-api-v1 3.1.0+c154966e77
	   |-- fabric-renderer-indigo 1.4.0+c154966e77
	   |-- fabric-renderer-registries-v1 3.2.44+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.33+b3afc78b77
	   |-- fabric-rendering-fluids-v1 3.0.26+b3afc78b77
	   |-- fabric-rendering-v0 1.1.47+df3654b377
	   |-- fabric-rendering-v1 3.0.6+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.5+ea08f9d877
	   |-- fabric-screen-api-v1 2.0.6+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.27+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.2.2+b3afc78b77
	   \-- fabric-transitive-access-wideners-v1 4.2.0+b3afc78b77
	- fabric-language-kotlin 1.10.0+kotlin.1.9.0
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.0
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.21.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.2
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.1
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.1
	- fabricloader 0.14.21
	- forgeconfigapiport 8.0.0
	- grass_kiss 1.20-fabric0.83.0-0.5.0
	- invmove 0.8.4
	- iris 1.6.4
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- java 17
	- minecraft 1.20.1
	- modelfix 1.14
	- modmenu 7.1.0
	- mousetweaks 2.25
	- pinglist 1.4
	- resourcify 1.1.0
	- sodium 0.4.10+build.27
	- sort 1.0.3
	- switcheroo 1.0.11
	- yet_another_config_lib_v3 3.0.3+1.20
	   |-- com_twelvemonkeys_common_common-image 3.9.4
	   |-- com_twelvemonkeys_common_common-io 3.9.4
	   |-- com_twelvemonkeys_common_common-lang 3.9.4
	   |-- com_twelvemonkeys_imageio_imageio-core 3.9.4
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.9.4
	   \-- com_twelvemonkeys_imageio_imageio-webp 3.9.4
[20:35:23] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/walth/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[20:35:23] [main/INFO]: Compatibility level set to JAVA_17
[20:35:24] [main/WARN]: Reference map 'InvMove-mc1.20_fabric-refmap.json' for invmove-fabric.mixins.json could not be read. If this is a development environment you can ignore this message
[20:35:24] [main/WARN]: [Satin] Iris is present, custom block renders will not work
[20:35:24] [main/INFO]: Loaded configuration file for Sodium: 33 options available, 3 override(s) found
[20:35:24] [main/INFO]: CameraOverhaul: Using modern mixin 'mirsario.cameraoverhaul.fabric.mixins.modern.CameraMixin'.
[20:35:24] [main/INFO]: CameraOverhaul: Using modern mixin 'mirsario.cameraoverhaul.fabric.mixins.modern.GameRendererMixin'.
[20:35:24] [main/INFO]: CameraOverhaul: Skipping legacy mixin 'mirsario.cameraoverhaul.fabric.mixins.legacy.LegacyCameraMixin'.
[20:35:24] [main/WARN]: Error loading class: net/fabricmc/fabric/impl/client/indigo/renderer/render/AbstractQuadRenderer (java.lang.ClassNotFoundException: net/fabricmc/fabric/impl/client/indigo/renderer/render/AbstractQuadRenderer)
[20:35:24] [main/WARN]: Force-disabling mixin 'features.entity.fast_render.MixinCuboid' as rule 'mixin.features.entity.fast_render' (added by mods [iris]) disables it and children
[20:35:24] [main/WARN]: Force-disabling mixin 'features.entity.fast_render.MixinModelPart' as rule 'mixin.features.entity.fast_render' (added by mods [iris]) disables it and children
[20:35:24] [main/WARN]: Force-disabling mixin 'features.gui.font.MixinGlyphRenderer' as rule 'mixin.features.gui.font' (added by mods [iris]) disables it and children
[20:35:24] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[20:35:25] [main/WARN]: Error loading class: org/jetbrains/annotations/ApiStatus$Internal (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$Internal)
[20:35:33] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 174 milliseconds
[20:35:36] [Render thread/INFO]: Launching a new process to probe the system configuration!
[20:35:36] [Render thread/INFO]: OpenGL Vendor: NVIDIA Corporation
[20:35:36] [Render thread/INFO]: OpenGL Renderer: NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2
[20:35:36] [Render thread/INFO]: OpenGL Version: 3.3.0 NVIDIA 536.23
[20:35:36] [Render thread/WARN]: Enabling workaround for NVIDIA graphics drivers on Windows (issue #1486)
[20:35:36] [Render thread/WARN]: One or more workarounds were enabled to prevent crashes or other issues on your system. You may need to update your graphics drivers.
[20:35:36] [Render thread/INFO]: Mixing MinecraftClientMixin from mixins.craftify.json into net.minecraft.class_310
[20:35:37] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:35:37] [Render thread/INFO]: Setting user: Tobias20084
[20:35:38] [Render thread/INFO]: CameraOverhaul: CameraSystem is ready.
[20:35:39] [Render thread/INFO]: Loading Config...
[20:35:40] [Render thread/INFO]: Loading ExplosiveConfig...
[20:35:40] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[20:35:40] [Worker-Main-1/INFO]: Checking mod updates...
[20:35:40] [Render thread/INFO]: [STDOUT]: [Mouse Tweaks] Main.initialize()
[20:35:40] [Render thread/INFO]: [STDOUT]: [Mouse Tweaks] Initialized.
[20:35:41] [Render thread/INFO]: Loaded Switcheroo!
[20:35:41] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[20:35:41] [ForkJoinPool.commonPool-worker-2/WARN]: [Iris Update Check] This version doesn't have an update index, skipping.
[20:35:41] [Worker-Main-1/INFO]: Update available for 'fabric-api@0.84.0+1.20.1', (-> 0.85.0+1.20.1)
[20:35:41] [Render thread/INFO]: Mixing MouseMixin from mixins.craftify.json into net.minecraft.class_312
[20:35:42] [Render thread/INFO]: Debug functionality is disabled.
[20:35:42] [Render thread/INFO]: ARB_direct_state_access detected, enabling DSA.
[20:35:42] [Render thread/WARN]: Tried to get boolean value for unknown option: TAA && !RETRO_FILTER, defaulting to true!
[20:35:42] [Render thread/WARN]: Tried to get boolean value for unknown option: FXAA && !RETRO_FILTER, defaulting to true!
[20:35:42] [Render thread/WARN]: Tried to get boolean value for unknown option: TAA && !RETRO_FILTER, defaulting to true!
[20:35:42] [Render thread/WARN]: Tried to get boolean value for unknown option: FXAA && !RETRO_FILTER, defaulting to true!
[20:35:42] [Render thread/WARN]: Tried to get boolean value for unknown option: FXAA && !RETRO_FILTER, defaulting to true!
[20:35:42] [Render thread/WARN]: Tried to get boolean value for unknown option: TAA && !RETRO_FILTER, defaulting to true!
[20:35:42] [Render thread/INFO]: Profile: Custom (+29 options changed by user)
[20:35:43] [Render thread/INFO]: Using shaderpack: BSL_v8.2.04.zip
[20:35:43] [Render thread/WARN]: Static binding violation: PRIVATE @Overwrite method method_23182 in sodium.mixins.json:features.item.MixinItemRenderer from mod sodium cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.
[20:35:44] [Render thread/INFO]: Hardware information:
[20:35:44] [Render thread/INFO]: CPU: 16x AMD Ryzen 7 3700X 8-Core Processor 
[20:35:44] [Render thread/INFO]: GPU: NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2 (Supports OpenGL 3.2.0 NVIDIA 536.23)
[20:35:44] [Render thread/INFO]: OS: Windows 11 (10.0)
[20:35:44] [Render thread/WARN]: Method overwrite conflict for method_3259 in sodium.mixins.json:features.clouds.MixinWorldRenderer from mod sodium, previously written by fabric.dev.notalpha.extendedclouds.mixin.WorldRendererMixin. Skipping method.
[20:35:45] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric (ambientsounds, appleskin, blur, borderlessmining, cameraoverhaul, cloth-config, creativecore, dynamiccrosshair, explosiveenhancement, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-tables-v1, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-networking-v0, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, forgeconfigapiport, grass_kiss, invmove, iris, midnightlib, modmenu, pinglist, resourcify, satin, sodium, sort, switcheroo, yaclx, yet_another_config_lib_v3), file/Bare+Bones+1.20.zip
[20:35:45] [Worker-Main-12/INFO]: Found unifont_all_no_pua-15.0.06.hex, loading
[20:35:45] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[20:35:45] [Worker-Main-3/WARN]: Invalid frame index on sprite minecraft:block/lava_still frame 10: 10
[20:35:45] [Worker-Main-8/WARN]: Unused frames in sprite minecraft:entity/conduit/wind: [22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
[20:35:45] [Worker-Main-6/WARN]: Unused frames in sprite minecraft:entity/conduit/wind_vertical: [22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
[20:35:45] [Worker-Main-7/WARN]: Texture minecraft:entity/conduit/open_eye with size 8x8 limits mip level from 4 to 3
[20:35:45] [Worker-Main-7/WARN]: minecraft:textures/atlas/blocks.png: dropping miplevel from 4 to 3, because of minimum power of two: 8
[20:35:45] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/stone.json' in resourcepack: 'file/Bare+Bones+1.20.zip' for variant: 'normal': Unknown blockstate property: 'normal'
[20:35:45] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/dirt.json' in resourcepack: 'file/Bare+Bones+1.20.zip' for variant: 'normal': Unknown blockstate property: 'normal'
[20:35:45] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/sand.json' in resourcepack: 'file/Bare+Bones+1.20.zip' for variant: 'normal': Unknown blockstate property: 'normal'
[20:35:45] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/red_sand.json' in resourcepack: 'file/Bare+Bones+1.20.zip' for variant: 'normal': Unknown blockstate property: 'normal'
[20:35:45] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/grass.json' in resourcepack: 'file/Bare+Bones+1.20.zip' for variant: 'normal': Unknown blockstate property: 'normal'
[20:35:45] [Render thread/INFO]: Starting custom uniform resolving
[20:35:46] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/white_concrete_powder.json' in resourcepack: 'file/Bare+Bones+1.20.zip' for variant: 'normal': Unknown blockstate property: 'normal'
[20:35:46] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/orange_concrete_powder.json' in resourcepack: 'file/Bare+Bones+1.20.zip' for variant: 'normal': Unknown blockstate property: 'normal'
[20:35:46] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/magenta_concrete_powder.json' in resourcepack: 'file/Bare+Bones+1.20.zip' for variant: 'normal': Unknown blockstate property: 'normal'
[20:35:46] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/light_blue_concrete_powder.json' in resourcepack: 'file/Bare+Bones+1.20.zip' for variant: 'normal': Unknown blockstate property: 'normal'
[20:35:46] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/yellow_concrete_powder.json' in resourcepack: 'file/Bare+Bones+1.20.zip' for variant: 'normal': Unknown blockstate property: 'normal'
[20:35:46] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/lime_concrete_powder.json' in resourcepack: 'file/Bare+Bones+1.20.zip' for variant: 'normal': Unknown blockstate property: 'normal'
[20:35:46] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/pink_concrete_powder.json' in resourcepack: 'file/Bare+Bones+1.20.zip' for variant: 'normal': Unknown blockstate property: 'normal'
[20:35:46] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/gray_concrete_powder.json' in resourcepack: 'file/Bare+Bones+1.20.zip' for variant: 'normal': Unknown blockstate property: 'normal'
[20:35:46] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/cyan_concrete_powder.json' in resourcepack: 'file/Bare+Bones+1.20.zip' for variant: 'normal': Unknown blockstate property: 'normal'
[20:35:46] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/purple_concrete_powder.json' in resourcepack: 'file/Bare+Bones+1.20.zip' for variant: 'normal': Unknown blockstate property: 'normal'
[20:35:46] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/blue_concrete_powder.json' in resourcepack: 'file/Bare+Bones+1.20.zip' for variant: 'normal': Unknown blockstate property: 'normal'
[20:35:46] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/brown_concrete_powder.json' in resourcepack: 'file/Bare+Bones+1.20.zip' for variant: 'normal': Unknown blockstate property: 'normal'
[20:35:46] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/green_concrete_powder.json' in resourcepack: 'file/Bare+Bones+1.20.zip' for variant: 'normal': Unknown blockstate property: 'normal'
[20:35:46] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/red_concrete_powder.json' in resourcepack: 'file/Bare+Bones+1.20.zip' for variant: 'normal': Unknown blockstate property: 'normal'
[20:35:46] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/black_concrete_powder.json' in resourcepack: 'file/Bare+Bones+1.20.zip' for variant: 'normal': Unknown blockstate property: 'normal'
[20:35:48] [Render thread/WARN]: [Patcher] gl_FragColor is not supported yet, please use gl_FragData! Assuming that the shaderpack author intended to use gl_FragData[0]...
[20:35:51] [Render thread/INFO]: Loaded AmbientEngine 'basic' v2.2.1. 11 dimension(s), 10 features, 11 groups, 33 regions, 59 sounds, 3 solids and 2 biome types
[20:35:52] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[20:35:52] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[20:35:52] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Lautsprecher (Focusrite USB Audio)
[20:35:52] [Render thread/INFO]: Sound engine started
[20:35:52] [Render thread/INFO]: Created: 512x1024x3 minecraft:textures/atlas/blocks.png-atlas
[20:35:52] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[20:35:52] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[20:35:52] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[20:35:52] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[20:35:52] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[20:35:52] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[20:35:52] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[20:35:52] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[20:35:53] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[20:35:53] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[20:35:53] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/paintings.png-atlas
[20:35:53] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[20:35:58] [Render thread/INFO]: Generating YACL screen
[20:35:58] [Render thread/INFO]: CameraOverhaul: Using implementation #0 for abstraction 'CreateText'.
[20:35:59] [Render thread/INFO]: Generating YACL screen
[20:36:45] [Render thread/WARN]: Warning! Mod craftify has a broken icon, loading default icon
[20:36:50] [Render thread/WARN]: Shader 953babc61b7d3bc9bfd95a62e6dc933dc8629aeb could not find uniform named subpixel_amount in the specified shader program.
[20:37:02] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:954) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[fabric-loader-0.14.21-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
Caused by: java.lang.NoSuchMethodError: 'void gg.essential.elementa.markdown.ParagraphConfig.<init>(float, float, float, boolean, boolean, float, int, kotlin.jvm.internal.DefaultConstructorMarker)'
	at dev.dediamondpro.resourcify.gui.projectpage.ProjectScreen$sideBar$8$2.invoke(ProjectScreen.kt:269) ~[Resourcify%20(1.20.x-fabric)-1.1.0.jar:?]
	at dev.dediamondpro.resourcify.gui.projectpage.ProjectScreen$sideBar$8$2.invoke(ProjectScreen.kt:258) ~[Resourcify%20(1.20.x-fabric)-1.1.0.jar:?]
	at gg.essential.elementa.components.Window.doDraw(Window.kt:69) ~[elementa-590-c4250c8341948a4b.jar:?]
	at gg.essential.elementa.components.Window.draw(Window.kt:57) ~[elementa-590-c4250c8341948a4b.jar:?]
	at gg.essential.elementa.WindowScreen.onDrawScreen(WindowScreen.kt:60) ~[elementa-590-c4250c8341948a4b.jar:?]
	at dev.dediamondpro.resourcify.gui.PaginatedScreen.onDrawScreen(PaginatedScreen.kt:52) ~[Resourcify%20(1.20.x-fabric)-1.1.0.jar:?]
	at gg.essential.universal.UScreen.onDrawScreen(UScreen.kt:259) ~[universalcraft-277-62fef53bf65c5df8.jar:?]
	at gg.essential.universal.UScreen$onDrawScreenCompat$1.invoke(UScreen.kt:265) ~[universalcraft-277-62fef53bf65c5df8.jar:?]
	at gg.essential.universal.UScreen$onDrawScreenCompat$1.invoke(UScreen.kt:263) ~[universalcraft-277-62fef53bf65c5df8.jar:?]
	at gg.essential.universal.UMatrixStack$Compat.runLegacyMethod(UMatrixStack.kt:304) ~[universalcraft-277-62fef53bf65c5df8.jar:?]
	at gg.essential.universal.UScreen.onDrawScreenCompat(UScreen.kt:263) ~[universalcraft-277-62fef53bf65c5df8.jar:?]
	at gg.essential.universal.UScreen.method_25394(UScreen.kt:82) ~[universalcraft-277-62fef53bf65c5df8.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:945) ~[client-intermediary.jar:?]
	... 6 more

**Comment by DeDiamondPro** [comment] 2023-07-06 19:39
Thank you for the report,
This is caused by a library conflict between craftify and resourcify. 
I have fixed this in commit 82291c7ab9e6bb01941f4a7b247265ea609be79f. Until the next release here is a zip with a patched build for every version that is affected: 
[Resourcify fixed.zip](https://github.com/DeDiamondPro/Resourcify/files/11971673/Resourcify.fixed.zip)

**Comment by DeDiamondPro** [comment] 2023-08-14 21:39
Fixed in 1.1.1

**Closed by DeDiamondPro** 2023-08-14 21:39 UTC
Labels: bug
