### ISSUE TITLE
Crash when trying to increase the volume

### ISSUE THREAD

**Issue by TRemill** [DeDiamondPro/Resourcify#17] opened 2023-08-15 02:47 UTC
**Technical Information**
Resourcify version: 1.1.1
Minecraft version: 1.20.1
Other mods (if relevant):

**Describe the bug**
When you try to add the overall volume of Minecraft, a crash occurs.

**Expected behavior**
Increase the volume of Minecraft.

**Steps to reproduce**
From the main menu, I go to settings, sound settings, and try to add volume

**Additional information**
[crash-2023-08-15_07.45.40-client.txt](https://github.com/DeDiamondPro/Resourcify/files/12340856/crash-2023-08-15_07.45.40-client.txt)

**Comment by TRemill** [comment] 2023-08-15 02:51
[latest.log](https://github.com/DeDiamondPro/Resourcify/files/12340865/latest.log)

Additional information
Mods:
fabric-api-0.87.0+1.20.1
fabric-language-kotlin-1.10.8+kotlin.1.9.0
Resourcify (1.20.x-fabric)-1.1.1

**Comment by TRemill** [comment] 2023-08-15 03:11
[crash-2023-08-15_08.09.03-client.txt](https://github.com/DeDiamondPro/Resourcify/files/12340932/crash-2023-08-15_08.09.03-client.txt)
I also add that the same effect when creating a new world, and specifically at the creation stage, the game mode change button causes a crash.

**Comment by DeDiamondPro** [comment] 2023-08-15 05:41
duplicate of #15

**Closed by DeDiamondPro** 2023-08-15 05:41 UTC
Labels: bug
