### ISSUE TITLE
Crash in ParentElementMixin caused by missing instanceof check

### ISSUE THREAD

**Issue by mxKeaton** [DeDiamondPro/Resourcify#15] opened 2023-08-14 21:25 UTC
**Technical Information**
Resourcify version: 1.1.1
Minecraft version: 1.19.2
Other mods (if relevant):

**Describe the bug**
After the update game crashes on inventory interactions.

**Expected behavior**
Does not make the game crash

**Steps to reproduce**
Install new update and either open the inventory or open a block inventory like furnaces or chests

**Additional information**
After only disabling this mod the issue did not occure + it started after updating

**Comment by DeDiamondPro** [comment] 2023-08-14 21:41
Hi,
I was unfortunately unable to reproduce this issue, could you please send the crash report, this can be found in `.minecraft/crash-reports`

**Comment by mxKeaton** [comment] 2023-08-14 23:13
It did not produce a crash log even though the issue was easily reproducable for me 3 times in a row. The game did not crash entirely and just became unresponsive (white screen + waiting for application) until I closed it manually. Also the regular logs do not help here either.

cropped part of the regular log during the "crash" right after loading into the world:
[23:21:20] [Render thread/INFO]: World Chunk Building: 303/314
[23:21:20] [Render thread/INFO]: World Chunk Building: 309/314
[23:21:20] [Render thread/INFO]: World Chunk Building: 315/314
[23:21:21] [Render thread/INFO]: Successfully pre-loaded the world!
[23:21:25] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 3944ms or 78 ticks behind
[23:21:44] [Server thread/INFO]: Saving and pausing game...
[23:21:44] [Server thread/INFO]: Saving chunks for level 'ServerLevel[ENDLICH!!!]'/minecraft:overworld
[23:21:44] [Server thread/INFO]: Saving grave backup data
[23:21:44] [Server thread/INFO]: Saving chunks for level 'ServerLevel[ENDLICH!!!]'/minecraft:the_nether
[23:21:44] [Server thread/INFO]: Saving chunks for level 'ServerLevel[ENDLICH!!!]'/minecraft:the_end
[23:21:44] [Server thread/INFO]: Saving chunks for level 'ServerLevel[ENDLICH!!!]'/deeperdarker:otherside
[23:21:47] [Render thread/INFO]: Minimap session finalized.
[23:21:47] [Render thread/INFO]: Finalizing world map session...
[23:21:47] [Thread-22/INFO]: World map force-cleaned!
[23:21:47] [Render thread/INFO]: World map session finalized.
[23:21:47] [Server thread/INFO]: xKeaton lost connection: Disconnected
[23:21:47] [Server thread/INFO]: xKeaton left the game
[23:21:47] [Server thread/INFO]: Stopping singleplayer server as player logged out
[23:21:47] [Server thread/INFO]: Stopping server

**Comment by craftish37** [comment] 2023-08-15 00:38
Hi, I got the same issue and confirmed that it was caused by updating Resourcify, [here](https://github.com/DeDiamondPro/Resourcify/files/12340399/2023-08-15-6.log) are my logs

**Comment by DeDiamondPro** [comment] 2023-08-15 05:49
Fixed in 1.1.2, this is a fabric only version since the forge version didn't have this issue

**Closed by DeDiamondPro** 2023-08-15 05:49 UTC
Labels: bug
